services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: dmgttm_backend
    volumes:
      - .:/app
    ports:
      - "6400:6400"
    env_file:
      - .env
    restart: unless-stopped
